device: cuda:4
output_dir: ./BioMiner/example_log
overwrite_bioactivity_text: true
overwrite_bioactivity_image: true
overwrite_structure_full: true
overwrite_structure_part: true
inference_given_structure_bioactivity: true
n_jobs: 64

data:
  parse_text_method: mineru # best: mineru [pypdf, mineru] 
  parse_image_method: mineru_contain # best: mineru_contain [pypdf, mineru_contain, mineru_sef]
  no_text_table: false
  prompt_path: ./BioMiner/commons/prompts

model:
  base_url:
  api_key:
  mol_detection_model: yolo
  ocsr_model: molscribe
  merge_strategy: direct
  text_mllm_type: gemini-2.0-flash 
  vision_mllm_type: gemini-2.0-flash 
  bioactivity_text_strategy: updated # best: updated
  bioactivity_image_strategy: updated # best: updated
  structure_full_strategy: updated-with-box-index # best: updated-with-box-index
  structure_part_strategy: updated-with-box-index # best: updated-with-box-index
  structure_full_split_molecule_num: 4 # best: 4
  structure_full_seg_image: true # best: true
  structure_full_seg_enlarge: 0.125 # best: 0.125
  structure_full_layout_seg: true # best: true
  structure_part_layout_seg: true # best: true
  structure_index_bbox_background: true # best: true
  structure_cot: false
  bioactivity_cot: false

test:
  comprehensive_evaluate: true
  complex_specific_evaluate: true
  top_n: 20
  pdb_name_path: ./BioVista/structure_annotation/labels/INDEX_general_PL_name.2020
  pdb_label_path: ./BioVista/structure_annotation/labels/INDEX_general_PL_data.2020
  pdb_structure_path: ./BioVista/structure_annotation/data
  labels_base_dir: ./BioVista/bioactivity_extraction
  dataset_name: labels
